services:
  serufuhosuto:
    build: .
    image: serufuhosuto-music-bot:local
    container_name: serufuhosuto
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./tmp:/app/tmp
