name: Manual Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (must match pom.xml)'
        required: true
        type: string
      notes:
        description: 'Release notes (optional)'
        required: false
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # ✅ Install ffmpeg
    - name: Install ffmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    # ✅ Install yt-dlp
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Build and Test with Maven
      run: mvn clean package

    - name: Get JAR name
      id: get_jar
      run: |
        echo "file=$(ls target/*.jar | grep -v 'original' | head -n 1)" >> "$GITHUB_OUTPUT"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: "v${{ github.event.inputs.version }}"
        body: ${{ github.event.inputs.notes }}
        files: ${{ steps.get_jar.outputs.file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}